language: node_js

matrix:
  include:
    - node_js: "8"

before_install:
  - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN -q;
  - git remote set-url origin git@github.com:opentable/design-tokens.git;
  - git config --global github.user nickbalestra;
  - git config --global github.token "$GH_TOKEN";

after_success:
  - if [ $TRAVIS_PULL_REQUEST == false ] && [ $TRAVIS_BRANCH == "master" ]; then
        git checkout master && npm run automatic-release;
      else
        npm run automatic-release-test;
      fi

notifications:
  email: false